# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C04
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $(CPPFLAGS) $< $(EXEFLAG)$@


Borland:  \
	StringStorage.exe \
	SmallString.exe \
	SmallString2.exe \
	StringIterators.exe \
	UhOh.exe \
	StrSize.exe \
	StringReplace.exe \
	Replace.exe \
	ReplaceAndGrow.exe \
	StringCharReplace.exe \
	AddStrings.exe \
	Sieve.exe \
	Find.exe \
	NewFind.exe \
	Rparse.exe \
	TrimTest.exe \
	ReprocessHTML.exe \
	HTMLStripper.exe \
	CompStr.exe \
	Compare.exe \
	Compare2.exe \
	StringIndexing.exe \
	BadStringIndexing.exe \
	CmpIter.exe \
	RevStr.exe \
	SiteMapConvert.exe

Microsoft:  \
	StringStorage.exe \
	StrSize.exe \
	StringReplace.exe \
	Replace.exe \
	ReplaceAndGrow.exe \
	StringCharReplace.exe \
	AddStrings.exe \
	Sieve.exe \
	Find.exe \
	NewFind.exe \
	Rparse.exe \
	TrimTest.exe \
	ReprocessHTML.exe \
	HTMLStripper.exe \
	CompStr.exe \
	Compare.exe \
	Compare2.exe \
	StringIndexing.exe \
	BadStringIndexing.exe \
	CmpIter.exe \
	RevStr.exe \
	SiteMapConvert.exe

g++295:  \
	StringStorage.exe \
	SmallString.exe \
	SmallString2.exe \
	StringIterators.exe \
	UhOh.exe \
	StrSize.exe \
	StringReplace.exe \
	Replace.exe \
	ReplaceAndGrow.exe \
	StringCharReplace.exe \
	AddStrings.exe \
	Sieve.exe \
	Find.exe \
	NewFind.exe \
	Rparse.exe \
	TrimTest.exe \
	ReprocessHTML.exe \
	HTMLStripper.exe \
	CompStr.exe \
	Compare.exe \
	StringIndexing.exe \
	BadStringIndexing.exe \
	CmpIter.exe \
	RevStr.exe \
	SiteMapConvert.exe

g++3:  \
	StringStorage.exe \
	SmallString.exe \
	SmallString2.exe \
	StringIterators.exe \
	UhOh.exe \
	StrSize.exe \
	StringReplace.exe \
	Replace.exe \
	ReplaceAndGrow.exe \
	StringCharReplace.exe \
	AddStrings.exe \
	Sieve.exe \
	Find.exe \
	NewFind.exe \
	Rparse.exe \
	TrimTest.exe \
	ReprocessHTML.exe \
	HTMLStripper.exe \
	CompStr.exe \
	Compare.exe \
	Compare2.exe \
	StringIndexing.exe \
	BadStringIndexing.exe \
	CmpIter.exe \
	RevStr.exe \
	SiteMapConvert.exe

edg:  \
	StringStorage.exe \
	SmallString.exe \
	SmallString2.exe \
	StringIterators.exe \
	UhOh.exe \
	StrSize.exe \
	StringReplace.exe \
	Replace.exe \
	ReplaceAndGrow.exe \
	StringCharReplace.exe \
	AddStrings.exe \
	Sieve.exe \
	Find.exe \
	NewFind.exe \
	Rparse.exe \
	TrimTest.exe \
	ReprocessHTML.exe \
	HTMLStripper.exe \
	CompStr.exe \
	Compare.exe \
	Compare2.exe \
	StringIndexing.exe \
	BadStringIndexing.exe \
	CmpIter.exe \
	RevStr.exe \
	SiteMapConvert.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


StringStorage.exe: ../TestSuite/Test.$(OBJEXT) StringStorage.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)StringStorage.exe StringStorage.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	StringStorage.exe
endif

StringStorage.$(OBJEXT): StringStorage.cpp
SmallString.exe: ../TestSuite/Test.$(OBJEXT) SmallString.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)SmallString.exe SmallString.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	SmallString.exe
endif

SmallString.$(OBJEXT): SmallString.cpp
SmallString2.exe: ../TestSuite/Test.$(OBJEXT) SmallString2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)SmallString2.exe SmallString2.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	SmallString2.exe
endif

SmallString2.$(OBJEXT): SmallString2.cpp
StringIterators.exe: ../TestSuite/Test.$(OBJEXT) StringIterators.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)StringIterators.exe StringIterators.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	StringIterators.exe
endif

StringIterators.$(OBJEXT): StringIterators.cpp
UhOh.exe: ../TestSuite/Test.$(OBJEXT) UhOh.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)UhOh.exe UhOh.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	UhOh.exe
endif

UhOh.$(OBJEXT): UhOh.cpp
StrSize.exe: ../TestSuite/Test.$(OBJEXT) StrSize.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)StrSize.exe StrSize.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	StrSize.exe
endif

StrSize.$(OBJEXT): StrSize.cpp
StringReplace.exe: ../TestSuite/Test.$(OBJEXT) StringReplace.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)StringReplace.exe StringReplace.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	StringReplace.exe
endif

StringReplace.$(OBJEXT): StringReplace.cpp
Replace.exe: ../TestSuite/Test.$(OBJEXT) Replace.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Replace.exe Replace.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Replace.exe
endif

Replace.$(OBJEXT): Replace.cpp
ReplaceAndGrow.exe: ../TestSuite/Test.$(OBJEXT) ReplaceAndGrow.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)ReplaceAndGrow.exe ReplaceAndGrow.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	ReplaceAndGrow.exe
endif

ReplaceAndGrow.$(OBJEXT): ReplaceAndGrow.cpp
StringCharReplace.exe: ../TestSuite/Test.$(OBJEXT) StringCharReplace.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)StringCharReplace.exe StringCharReplace.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	StringCharReplace.exe
endif

StringCharReplace.$(OBJEXT): StringCharReplace.cpp
AddStrings.exe: ../TestSuite/Test.$(OBJEXT) AddStrings.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)AddStrings.exe AddStrings.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	AddStrings.exe
endif

AddStrings.$(OBJEXT): AddStrings.cpp
Sieve.exe: ../TestSuite/Test.$(OBJEXT) Sieve.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Sieve.exe Sieve.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Sieve.exe
endif

Sieve.$(OBJEXT): Sieve.cpp
Find.exe: ../TestSuite/Test.$(OBJEXT) Find.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Find.exe Find.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Find.exe
endif

Find.$(OBJEXT): Find.cpp
NewFind.exe: ../TestSuite/Test.$(OBJEXT) NewFind.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)NewFind.exe NewFind.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	NewFind.exe
endif

NewFind.$(OBJEXT): NewFind.cpp
Rparse.exe: ../TestSuite/Test.$(OBJEXT) Rparse.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Rparse.exe Rparse.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Rparse.exe
endif

Rparse.$(OBJEXT): Rparse.cpp
TrimTest.exe: ../TestSuite/Test.$(OBJEXT) TrimTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)TrimTest.exe TrimTest.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	TrimTest.exe
endif

TrimTest.$(OBJEXT): TrimTest.cpp
ReprocessHTML.exe: ReprocessHTML.cpp

HTMLStripper.exe: HTMLStripper.cpp

CompStr.exe: ../TestSuite/Test.$(OBJEXT) CompStr.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)CompStr.exe CompStr.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	CompStr.exe
endif

CompStr.$(OBJEXT): CompStr.cpp
Compare.exe: ../TestSuite/Test.$(OBJEXT) Compare.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Compare.exe Compare.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Compare.exe
endif

Compare.$(OBJEXT): Compare.cpp
Compare2.exe: ../TestSuite/Test.$(OBJEXT) Compare2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Compare2.exe Compare2.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Compare2.exe
endif

Compare2.$(OBJEXT): Compare2.cpp
StringIndexing.exe: ../TestSuite/Test.$(OBJEXT) StringIndexing.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)StringIndexing.exe StringIndexing.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	StringIndexing.exe
endif

StringIndexing.$(OBJEXT): StringIndexing.cpp
BadStringIndexing.exe: ../TestSuite/Test.$(OBJEXT) BadStringIndexing.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)BadStringIndexing.exe BadStringIndexing.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	BadStringIndexing.exe
endif

BadStringIndexing.$(OBJEXT): BadStringIndexing.cpp
CmpIter.exe: ../TestSuite/Test.$(OBJEXT) CmpIter.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)CmpIter.exe CmpIter.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	CmpIter.exe
endif

CmpIter.$(OBJEXT): CmpIter.cpp
RevStr.exe: ../TestSuite/Test.$(OBJEXT) RevStr.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)RevStr.exe RevStr.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	RevStr.exe
endif

RevStr.$(OBJEXT): RevStr.cpp
SiteMapConvert.exe: SiteMapConvert.cpp

