set_property -dict {LOC AC18 IOSTANDARD LVCMOS18} [get_ports clk]
set_property -dict {LOC W13 IOSTANDARD LVCMOS18} [get_ports rstn]
set_property -dict {LOC M24 IOSTANDARD LVCMOS33} [get_ports SEGLED_CLK]
set_property -dict {LOC M20 IOSTANDARD LVCMOS33} [get_ports SEGLED_CLR]
set_property -dict {LOC L24 IOSTANDARD LVCMOS33} [get_ports SEGLED_DO]
set_property -dict {LOC R18 IOSTANDARD LVCMOS33} [get_ports SEGLED_PEN]
set_property -dict {LOC N26 IOSTANDARD LVCMOS33} [get_ports LED_CLK]
set_property -dict {LOC N24 IOSTANDARD LVCMOS33} [get_ports LED_CLR]
set_property -dict {LOC M26 IOSTANDARD LVCMOS33} [get_ports LED_DO]
set_property -dict {LOC P18 IOSTANDARD LVCMOS33} [get_ports LED_PEN]
set_property -dict {LOC V17 IOSTANDARD LVCMOS18} [get_ports BTN_X[0]]
set_property -dict {LOC W18 IOSTANDARD LVCMOS18} [get_ports BTN_X[1]]
set_property -dict {LOC W19 IOSTANDARD LVCMOS18} [get_ports BTN_X[2]]
set_property -dict {LOC W15 IOSTANDARD LVCMOS18} [get_ports BTN_X[3]]
set_property -dict {LOC W16 IOSTANDARD  LVCMOS18}  [get_ports BTN_X[4]]
set_property -dict {LOC V18 IOSTANDARD  LVCMOS18}  [get_ports BTN_Y[0]]
set_property -dict {LOC V19 IOSTANDARD  LVCMOS18}  [get_ports BTN_Y[1]]
set_property -dict {LOC V14 IOSTANDARD LVCMOS18} [get_ports BTN_Y[2]]
set_property -dict {LOC W14 IOSTANDARD  LVCMOS18} [get_ports BTN_Y[3]]

set_property PULLUP true [get_ports BTN_X[0]]
set_property PULLUP true [get_ports BTN_X[1]]
set_property PULLUP true [get_ports BTN_X[2]]
set_property PULLUP true [get_ports BTN_X[3]]
set_property PULLUP true [get_ports BTN_X[4]]
set_property PULLUP true [get_ports BTN_Y[0]]
set_property PULLUP true [get_ports BTN_Y[2]]
set_property PULLUP true [get_ports BTN_Y[3]]

set_property PULLUP true [get_ports BTN_Y[1]]

set_property -dict {LOC N18 IOSTANDARD  LVCMOS33} [get_ports ps2_clk]
set_property -dict {LOC M19 IOSTANDARD  LVCMOS33} [get_ports ps2_data]



set_property -dict {LOC AA10 IOSTANDARD LVCMOS15} [get_ports SW[0]]
set_property -dict {LOC AB10 IOSTANDARD LVCMOS15} [get_ports SW[1]]
set_property -dict {LOC AA13 IOSTANDARD LVCMOS15} [get_ports SW[2]]
set_property -dict {LOC AA12 IOSTANDARD LVCMOS15} [get_ports SW[3]]
set_property -dict {LOC Y13 IOSTANDARD LVCMOS15} [get_ports SW[4]]
set_property -dict {LOC Y12 IOSTANDARD LVCMOS15} [get_ports SW[5]]
set_property -dict {LOC AD11 IOSTANDARD LVCMOS15} [get_ports SW[6]]
set_property -dict {LOC AD10 IOSTANDARD LVCMOS15} [get_ports SW[7]]
set_property -dict {LOC AE10 IOSTANDARD LVCMOS15} [get_ports SW[8]]
set_property -dict {LOC AE12 IOSTANDARD LVCMOS15} [get_ports SW[9]]
set_property -dict {LOC AF12 IOSTANDARD LVCMOS15} [get_ports SW[10]]
set_property -dict {LOC AE8 IOSTANDARD LVCMOS15} [get_ports SW[11]]
set_property -dict {LOC AF8 IOSTANDARD LVCMOS15} [get_ports SW[12]]
set_property -dict {LOC AE13 IOSTANDARD LVCMOS15} [get_ports SW[13]]
set_property -dict {LOC AF13 IOSTANDARD LVCMOS15} [get_ports SW[14]]
set_property -dict {LOC AF10 IOSTANDARD LVCMOS15} [get_ports SW[15]]
set_property -dict {LOC AF24 IOSTANDARD LVCMOS33} [get_ports buzzer]
set_property -dict {LOC T20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports b[0]]
set_property -dict {LOC R20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports b[1]]
set_property -dict {LOC T22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports b[2]]
set_property -dict {LOC T23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports b[3]]
set_property -dict {LOC R22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports g[0]]
set_property -dict {LOC R23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports g[1]]
set_property -dict {LOC T24 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports g[2]]
set_property -dict {LOC T25 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports g[3]]
set_property -dict {LOC N21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports r[0]]
set_property -dict {LOC N22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports r[1]]
set_property -dict {LOC R21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports r[2]]
set_property -dict {LOC P21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports r[3]]
set_property -dict {LOC M22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports hs]
set_property -dict {LOC M21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports vs]

