# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C06
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $(CPPFLAGS) $< $(EXEFLAG)$@


Borland:  \
	TypenamedID.exe \
	UsingTypename.exe \
	Getmem.exe \
	TemplateFunctionAddress.exe \
	applyGromit.exe \
	TemplateTemplate.exe \
	applyGromit2.exe \
	Sorted.exe \
	NobloatTest.exe \
	ExplicitInstantiation.exe \
	DelayedInstantiation.exe

Microsoft:  \
	TypenamedID.exe \
	UsingTypename.exe \
	Getmem.exe \
	TemplateFunctionAddress.exe \
	applyGromit.exe \
	NobloatTest.exe \
	DelayedInstantiation.exe

g++295:  \
	TypenamedID.exe \
	UsingTypename.exe \
	stringConvTest.exe \
	Getmem.exe \
	ArraySize.exe \
	TemplateFunctionAddress.exe \
	applyGromit.exe \
	TemplateTemplate.exe \
	NobloatTest.exe \
	DelayedInstantiation.exe

g++3:  \
	TypenamedID.exe \
	UsingTypename.exe \
	stringConvTest.exe \
	Getmem.exe \
	ArraySize.exe \
	TemplateFunctionAddress.exe \
	applyGromit.exe \
	TemplateTemplate.exe \
	Sorted.exe \
	NobloatTest.exe \
	ExplicitInstantiation.exe \
	DelayedInstantiation.exe

edg:  \
	TypenamedID.exe \
	UsingTypename.exe \
	stringConvTest.exe \
	Getmem.exe \
	ArraySize.exe \
	TemplateFunctionAddress.exe \
	applyGromit.exe \
	TemplateTemplate.exe \
	applyGromit2.exe \
	Sorted.exe \
	NobloatTest.exe \
	ExplicitInstantiation.exe \
	DelayedInstantiation.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


TypenamedID.exe: ../TestSuite/Test.$(OBJEXT) TypenamedID.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)TypenamedID.exe TypenamedID.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	TypenamedID.exe
endif

TypenamedID.$(OBJEXT): TypenamedID.cpp
UsingTypename.exe: ../TestSuite/Test.$(OBJEXT) UsingTypename.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)UsingTypename.exe UsingTypename.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	UsingTypename.exe
endif

UsingTypename.$(OBJEXT): UsingTypename.cpp
stringConvTest.exe: ../TestSuite/Test.$(OBJEXT) stringConvTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)stringConvTest.exe stringConvTest.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	stringConvTest.exe
endif

stringConvTest.$(OBJEXT): stringConvTest.cpp
Getmem.exe: ../TestSuite/Test.$(OBJEXT) Getmem.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Getmem.exe Getmem.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Getmem.exe
endif

Getmem.$(OBJEXT): Getmem.cpp
ArraySize.exe: ../TestSuite/Test.$(OBJEXT) ArraySize.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)ArraySize.exe ArraySize.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	ArraySize.exe
endif

ArraySize.$(OBJEXT): ArraySize.cpp
TemplateFunctionAddress.exe: ../TestSuite/Test.$(OBJEXT) TemplateFunctionAddress.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)TemplateFunctionAddress.exe TemplateFunctionAddress.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	TemplateFunctionAddress.exe
endif

TemplateFunctionAddress.$(OBJEXT): TemplateFunctionAddress.cpp
applyGromit.exe: ../TestSuite/Test.$(OBJEXT) applyGromit.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)applyGromit.exe applyGromit.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	applyGromit.exe
endif

applyGromit.$(OBJEXT): applyGromit.cpp
TemplateTemplate.exe: ../TestSuite/Test.$(OBJEXT) TemplateTemplate.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)TemplateTemplate.exe TemplateTemplate.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	TemplateTemplate.exe
endif

TemplateTemplate.$(OBJEXT): TemplateTemplate.cpp
applyGromit2.exe: ../TestSuite/Test.$(OBJEXT) applyGromit2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)applyGromit2.exe applyGromit2.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	applyGromit2.exe
endif

applyGromit2.$(OBJEXT): applyGromit2.cpp
Sorted.exe: ../TestSuite/Test.$(OBJEXT) Sorted.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Sorted.exe Sorted.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Sorted.exe
endif

Sorted.$(OBJEXT): Sorted.cpp
NobloatTest.exe: ../TestSuite/Test.$(OBJEXT) NobloatTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)NobloatTest.exe NobloatTest.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	NobloatTest.exe
endif

NobloatTest.$(OBJEXT): NobloatTest.cpp
ExplicitInstantiation.exe: ../TestSuite/Test.$(OBJEXT) ExplicitInstantiation.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)ExplicitInstantiation.exe ExplicitInstantiation.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	ExplicitInstantiation.exe
endif

ExplicitInstantiation.$(OBJEXT): ExplicitInstantiation.cpp
DelayedInstantiation.exe: ../TestSuite/Test.$(OBJEXT) DelayedInstantiation.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)DelayedInstantiation.exe DelayedInstantiation.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	DelayedInstantiation.exe
endif

DelayedInstantiation.$(OBJEXT): DelayedInstantiation.cpp
