# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C08
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $(CPPFLAGS) $< $(EXEFLAG)$@


Borland:  \
	FuncObject.exe \
	FunctionObjects.exe \
	Binder1.exe \
	Binder2.exe \
	Binder3.exe \
	Binder4.exe \
	RandGenTest.exe \
	MemFun1.exe \
	MemFun2.exe \
	MemFun3.exe \
	NoCompose.exe \
	FillGenerateTest.exe \
	Counting.exe \
	Manipulations.exe \
	SearchReplace.exe \
	Comparison.exe \
	SortTest.exe \
	SortedSearchTest.exe \
	MergeTest.exe \
	SetOperations.exe \
	ForEach.exe \
	Transform.exe \
	CalcInventory.exe \
	TransformNames.exe \
	SpecialList.exe \
	NumericTest.exe

Microsoft:  \
	FuncObject.exe \
	FunctionObjects.exe \
	Binder1.exe \
	Binder2.exe \
	Binder3.exe \
	Binder4.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	NoCompose.exe \
	Comparison.exe \
	MergeTest.exe \
	NumericTest.exe

g++295:  \
	FuncObject.exe \
	FunctionObjects.exe \
	Binder1.exe \
	Binder2.exe \
	Binder3.exe \
	RandGenTest.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	MemFun1.exe \
	MemFun2.exe \
	MemFun3.exe \
	MemFun4.exe \
	Compose2.exe \
	NoCompose.exe \
	FillGenerateTest.exe \
	MergeTest.exe \
	SetOperations.exe \
	Transform.exe

g++3:  \
	FuncObject.exe \
	FunctionObjects.exe \
	Binder2.exe \
	Binder3.exe \
	Binder4.exe \
	RandGenTest.exe \
	PtrFun1.exe \
	MemFun1.exe \
	MemFun2.exe \
	MemFun3.exe \
	MemFun4.exe \
	Compose2.exe \
	NoCompose.exe \
	FillGenerateTest.exe \
	Counting.exe \
	Manipulations.exe \
	SearchReplace.exe \
	Comparison.exe \
	Removing.exe \
	SortTest.exe \
	SortedSearchTest.exe \
	MergeTest.exe \
	SetOperations.exe \
	Transform.exe \
	CalcInventory.exe \
	TransformNames.exe \
	SpecialList.exe \
	NumericTest.exe

edg:  \
	FuncObject.exe \
	FunctionObjects.exe \
	Binder1.exe \
	Binder2.exe \
	Binder3.exe \
	Binder4.exe \
	RandGenTest.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	MemFun1.exe \
	MemFun2.exe \
	FindBlanks.exe \
	MemFun3.exe \
	MemFun4.exe \
	Compose2.exe \
	NoCompose.exe \
	FillGenerateTest.exe \
	Counting.exe \
	Manipulations.exe \
	SearchReplace.exe \
	Comparison.exe \
	Removing.exe \
	SortTest.exe \
	SortedSearchTest.exe \
	MergeTest.exe \
	SetOperations.exe \
	ForEach.exe \
	Transform.exe \
	CalcInventory.exe \
	TransformNames.exe \
	SpecialList.exe \
	NumericTest.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


FuncObject.exe: ../TestSuite/Test.$(OBJEXT) FuncObject.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)FuncObject.exe FuncObject.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	FuncObject.exe
endif

FuncObject.$(OBJEXT): FuncObject.cpp
FunctionObjects.exe: ../TestSuite/Test.$(OBJEXT) FunctionObjects.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)FunctionObjects.exe FunctionObjects.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	FunctionObjects.exe
endif

FunctionObjects.$(OBJEXT): FunctionObjects.cpp
Binder1.exe: ../TestSuite/Test.$(OBJEXT) Binder1.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Binder1.exe Binder1.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Binder1.exe
endif

Binder1.$(OBJEXT): Binder1.cpp
Binder2.exe: ../TestSuite/Test.$(OBJEXT) Binder2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Binder2.exe Binder2.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Binder2.exe
endif

Binder2.$(OBJEXT): Binder2.cpp
Binder3.exe: ../TestSuite/Test.$(OBJEXT) Binder3.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Binder3.exe Binder3.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Binder3.exe
endif

Binder3.$(OBJEXT): Binder3.cpp
Binder4.exe: ../TestSuite/Test.$(OBJEXT) Binder4.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Binder4.exe Binder4.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Binder4.exe
endif

Binder4.$(OBJEXT): Binder4.cpp
RandGenTest.exe: ../TestSuite/Test.$(OBJEXT) RandGenTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)RandGenTest.exe RandGenTest.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	RandGenTest.exe
endif

RandGenTest.$(OBJEXT): RandGenTest.cpp
PtrFun1.exe: ../TestSuite/Test.$(OBJEXT) PtrFun1.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)PtrFun1.exe PtrFun1.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	PtrFun1.exe
endif

PtrFun1.$(OBJEXT): PtrFun1.cpp
PtrFun2.exe: ../TestSuite/Test.$(OBJEXT) PtrFun2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)PtrFun2.exe PtrFun2.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	PtrFun2.exe
endif

PtrFun2.$(OBJEXT): PtrFun2.cpp
MemFun1.exe: ../TestSuite/Test.$(OBJEXT) MemFun1.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)MemFun1.exe MemFun1.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	MemFun1.exe
endif

MemFun1.$(OBJEXT): MemFun1.cpp
MemFun2.exe: ../TestSuite/Test.$(OBJEXT) MemFun2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)MemFun2.exe MemFun2.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	MemFun2.exe
endif

MemFun2.$(OBJEXT): MemFun2.cpp
FindBlanks.exe: ../TestSuite/Test.$(OBJEXT) FindBlanks.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)FindBlanks.exe FindBlanks.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	FindBlanks.exe
endif

FindBlanks.$(OBJEXT): FindBlanks.cpp
MemFun3.exe: ../TestSuite/Test.$(OBJEXT) MemFun3.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)MemFun3.exe MemFun3.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	MemFun3.exe
endif

MemFun3.$(OBJEXT): MemFun3.cpp
MemFun4.exe: ../TestSuite/Test.$(OBJEXT) MemFun4.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)MemFun4.exe MemFun4.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	MemFun4.exe
endif

MemFun4.$(OBJEXT): MemFun4.cpp
Compose2.exe: ../TestSuite/Test.$(OBJEXT) Compose2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Compose2.exe Compose2.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Compose2.exe
endif

Compose2.$(OBJEXT): Compose2.cpp
NoCompose.exe: ../TestSuite/Test.$(OBJEXT) NoCompose.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)NoCompose.exe NoCompose.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	NoCompose.exe
endif

NoCompose.$(OBJEXT): NoCompose.cpp
FillGenerateTest.exe: ../TestSuite/Test.$(OBJEXT) FillGenerateTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)FillGenerateTest.exe FillGenerateTest.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	FillGenerateTest.exe
endif

FillGenerateTest.$(OBJEXT): FillGenerateTest.cpp
Counting.exe: ../TestSuite/Test.$(OBJEXT) Counting.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Counting.exe Counting.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Counting.exe
endif

Counting.$(OBJEXT): Counting.cpp
Manipulations.exe: ../TestSuite/Test.$(OBJEXT) Manipulations.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Manipulations.exe Manipulations.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Manipulations.exe
endif

Manipulations.$(OBJEXT): Manipulations.cpp
SearchReplace.exe: ../TestSuite/Test.$(OBJEXT) SearchReplace.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)SearchReplace.exe SearchReplace.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	SearchReplace.exe
endif

SearchReplace.$(OBJEXT): SearchReplace.cpp
Comparison.exe: ../TestSuite/Test.$(OBJEXT) Comparison.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Comparison.exe Comparison.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Comparison.exe
endif

Comparison.$(OBJEXT): Comparison.cpp
Removing.exe: ../TestSuite/Test.$(OBJEXT) Removing.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Removing.exe Removing.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Removing.exe
endif

Removing.$(OBJEXT): Removing.cpp
SortTest.exe: ../C07/StreamTokenizer.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) SortTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)SortTest.exe SortTest.$(OBJEXT) ../C07/StreamTokenizer.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	SortTest.exe
endif

SortTest.$(OBJEXT): SortTest.cpp
SortedSearchTest.exe: ../C07/StreamTokenizer.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) SortedSearchTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)SortedSearchTest.exe SortedSearchTest.$(OBJEXT) ../C07/StreamTokenizer.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	SortedSearchTest.exe
endif

SortedSearchTest.$(OBJEXT): SortedSearchTest.cpp
MergeTest.exe: ../TestSuite/Test.$(OBJEXT) MergeTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)MergeTest.exe MergeTest.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	MergeTest.exe
endif

MergeTest.$(OBJEXT): MergeTest.cpp
SetOperations.exe: ../TestSuite/Test.$(OBJEXT) SetOperations.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)SetOperations.exe SetOperations.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	SetOperations.exe
endif

SetOperations.$(OBJEXT): SetOperations.cpp
ForEach.exe: ../TestSuite/Test.$(OBJEXT) ForEach.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)ForEach.exe ForEach.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	ForEach.exe
endif

ForEach.$(OBJEXT): ForEach.cpp
Transform.exe: ../TestSuite/Test.$(OBJEXT) Transform.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Transform.exe Transform.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Transform.exe
endif

Transform.$(OBJEXT): Transform.cpp
CalcInventory.exe: ../TestSuite/Test.$(OBJEXT) CalcInventory.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)CalcInventory.exe CalcInventory.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	CalcInventory.exe
endif

CalcInventory.$(OBJEXT): CalcInventory.cpp
TransformNames.exe: ../TestSuite/Test.$(OBJEXT) TransformNames.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)TransformNames.exe TransformNames.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	TransformNames.exe
endif

TransformNames.$(OBJEXT): TransformNames.cpp
SpecialList.exe: ../TestSuite/Test.$(OBJEXT) SpecialList.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)SpecialList.exe SpecialList.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	SpecialList.exe
endif

SpecialList.$(OBJEXT): SpecialList.cpp
NumericTest.exe: ../TestSuite/Test.$(OBJEXT) NumericTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)NumericTest.exe NumericTest.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	NumericTest.exe
endif

NumericTest.$(OBJEXT): NumericTest.cpp
