# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C09
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $(CPPFLAGS) $< $(EXEFLAG)$@


Borland:  \
	Rtshapes.exe \
	TypeidAndBuiltins.exe \
	RTTIandNesting.exe \
	RTTIWithoutPolymorphism.exe \
	DynamicCast.exe \
	Voidrtti.exe \
	ConstructorOrder.exe \
	RTTIwithReferences.exe \
	RTTIwithExceptions.exe \
	RTTIandMultipleInheritance.exe \
	Recycle2.exe \
	Selfrtti.exe

Microsoft:  \
	Rtshapes.exe \
	TypeidAndBuiltins.exe \
	RTTIandNesting.exe \
	RTTIWithoutPolymorphism.exe \
	DynamicCast.exe \
	Voidrtti.exe \
	ConstructorOrder.exe \
	RTTIwithReferences.exe \
	RTTIwithExceptions.exe \
	RTTIandMultipleInheritance.exe \
	Recycle2.exe \
	Selfrtti.exe

g++295:  \
	Rtshapes.exe \
	TypeidAndBuiltins.exe \
	RTTIandNesting.exe \
	RTTIWithoutPolymorphism.exe \
	DynamicCast.exe \
	Voidrtti.exe \
	ConstructorOrder.exe \
	RTTIwithReferences.exe \
	RTTIwithExceptions.exe \
	RTTIandMultipleInheritance.exe \
	Recycle2.exe \
	Selfrtti.exe

g++3:  \
	Rtshapes.exe \
	TypeidAndBuiltins.exe \
	RTTIandNesting.exe \
	RTTIWithoutPolymorphism.exe \
	DynamicCast.exe \
	Voidrtti.exe \
	ConstructorOrder.exe \
	RTTIwithReferences.exe \
	RTTIwithExceptions.exe \
	RTTIandMultipleInheritance.exe \
	Recycle2.exe \
	Selfrtti.exe

edg:  \
	Rtshapes.exe \
	TypeidAndBuiltins.exe \
	RTTIandNesting.exe \
	RTTIWithoutPolymorphism.exe \
	DynamicCast.exe \
	Voidrtti.exe \
	ConstructorOrder.exe \
	RTTIwithReferences.exe \
	RTTIwithExceptions.exe \
	RTTIandMultipleInheritance.exe \
	Recycle2.exe \
	Selfrtti.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


Rtshapes.exe: ../TestSuite/Test.$(OBJEXT) Rtshapes.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Rtshapes.exe Rtshapes.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Rtshapes.exe
endif

Rtshapes.$(OBJEXT): Rtshapes.cpp
TypeidAndBuiltins.exe: ../TestSuite/Test.$(OBJEXT) TypeidAndBuiltins.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)TypeidAndBuiltins.exe TypeidAndBuiltins.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	TypeidAndBuiltins.exe
endif

TypeidAndBuiltins.$(OBJEXT): TypeidAndBuiltins.cpp
RTTIandNesting.exe: ../TestSuite/Test.$(OBJEXT) RTTIandNesting.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)RTTIandNesting.exe RTTIandNesting.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	RTTIandNesting.exe
endif

RTTIandNesting.$(OBJEXT): RTTIandNesting.cpp
RTTIWithoutPolymorphism.exe: ../TestSuite/Test.$(OBJEXT) RTTIWithoutPolymorphism.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)RTTIWithoutPolymorphism.exe RTTIWithoutPolymorphism.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	RTTIWithoutPolymorphism.exe
endif

RTTIWithoutPolymorphism.$(OBJEXT): RTTIWithoutPolymorphism.cpp
DynamicCast.exe: ../TestSuite/Test.$(OBJEXT) DynamicCast.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)DynamicCast.exe DynamicCast.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	DynamicCast.exe
endif

DynamicCast.$(OBJEXT): DynamicCast.cpp
Voidrtti.exe: ../TestSuite/Test.$(OBJEXT) Voidrtti.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Voidrtti.exe Voidrtti.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Voidrtti.exe
endif

Voidrtti.$(OBJEXT): Voidrtti.cpp
ConstructorOrder.exe: ../TestSuite/Test.$(OBJEXT) ConstructorOrder.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)ConstructorOrder.exe ConstructorOrder.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	ConstructorOrder.exe
endif

ConstructorOrder.$(OBJEXT): ConstructorOrder.cpp
RTTIwithReferences.exe: ../TestSuite/Test.$(OBJEXT) RTTIwithReferences.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)RTTIwithReferences.exe RTTIwithReferences.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	RTTIwithReferences.exe
endif

RTTIwithReferences.$(OBJEXT): RTTIwithReferences.cpp
RTTIwithExceptions.exe: ../TestSuite/Test.$(OBJEXT) RTTIwithExceptions.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)RTTIwithExceptions.exe RTTIwithExceptions.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	RTTIwithExceptions.exe
endif

RTTIwithExceptions.$(OBJEXT): RTTIwithExceptions.cpp
RTTIandMultipleInheritance.exe: ../TestSuite/Test.$(OBJEXT) RTTIandMultipleInheritance.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)RTTIandMultipleInheritance.exe RTTIandMultipleInheritance.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	RTTIandMultipleInheritance.exe
endif

RTTIandMultipleInheritance.$(OBJEXT): RTTIandMultipleInheritance.cpp
Recycle2.exe: ../TestSuite/Test.$(OBJEXT) Recycle2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Recycle2.exe Recycle2.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Recycle2.exe
endif

Recycle2.$(OBJEXT): Recycle2.cpp
Selfrtti.exe: ../TestSuite/Test.$(OBJEXT) Selfrtti.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Selfrtti.exe Selfrtti.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Selfrtti.exe
endif

Selfrtti.$(OBJEXT): Selfrtti.cpp
