# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C05
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $(CPPFLAGS) $< $(EXEFLAG)$@


Borland:  \
	FileClass.$(OBJEXT) \
	FileClassTest.exe \
	Iosexamp.exe \
	Strfile.exe \
	Stype.exe \
	Sbufget.exe \
	Seeking.exe \
	Iofile.exe \
	Istring.exe \
	Ostring.exe \
	Walrus.exe \
	Strmove.exe \
	Format.exe \
	Manips.exe \
	nl.exe \
	Effector.exe \
	Makemain.exe \
	Cppcheck.exe \
	Showerr.exe \
	Datalog.$(OBJEXT) \
	Datagen.exe \
	Datascan.exe \
	NumberPhotos.exe \
	Breakup.exe

Microsoft:  \
	Iosexamp.exe \
	Strfile.exe \
	Stype.exe \
	Sbufget.exe \
	Seeking.exe \
	Iofile.exe \
	Istring.exe \
	Ostring.exe \
	Walrus.exe \
	Strmove.exe \
	Format.exe \
	Manips.exe \
	nl.exe \
	Effector.exe \
	Makemain.exe \
	Cppcheck.exe \
	Showerr.exe \
	Datalog.$(OBJEXT) \
	Datagen.exe \
	Datascan.exe \
	NumberPhotos.exe \
	Breakup.exe

g++295:  \
	FileClass.$(OBJEXT) \
	FileClassTest.exe \
	Iosexamp.exe \
	Strfile.exe \
	Stype.exe \
	Seeking.exe \
	Iofile.exe \
	Istring.exe \
	Ostring.exe \
	Walrus.exe \
	Strmove.exe \
	Format.exe \
	Manips.exe \
	nl.exe \
	Effector.exe \
	Makemain.exe \
	Cppcheck.exe \
	Showerr.exe \
	Datalog.$(OBJEXT) \
	Datagen.exe \
	Datascan.exe \
	NumberPhotos.exe \
	Breakup.exe

g++3:  \
	FileClass.$(OBJEXT) \
	FileClassTest.exe \
	Iosexamp.exe \
	Strfile.exe \
	Stype.exe \
	Sbufget.exe \
	Seeking.exe \
	Iofile.exe \
	Istring.exe \
	Ostring.exe \
	Walrus.exe \
	Strmove.exe \
	nl.exe \
	Effector.exe \
	Makemain.exe \
	Cppcheck.exe \
	Showerr.exe \
	Datalog.$(OBJEXT) \
	Datagen.exe \
	Datascan.exe \
	NumberPhotos.exe \
	Breakup.exe

edg:  \
	FileClass.$(OBJEXT) \
	FileClassTest.exe \
	Iosexamp.exe \
	Strfile.exe \
	Stype.exe \
	Sbufget.exe \
	Seeking.exe \
	Iofile.exe \
	Istring.exe \
	Ostring.exe \
	Walrus.exe \
	Strmove.exe \
	Format.exe \
	Manips.exe \
	nl.exe \
	Effector.exe \
	Makemain.exe \
	Cppcheck.exe \
	Showerr.exe \
	Datalog.$(OBJEXT) \
	Datagen.exe \
	Datascan.exe \
	NumberPhotos.exe \
	Breakup.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


FileClass.$(OBJEXT): FileClass.cpp

FileClassTest.exe: FileClass.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) FileClassTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)FileClassTest.exe FileClassTest.$(OBJEXT) FileClass.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	FileClassTest.exe
endif

FileClassTest.$(OBJEXT): FileClassTest.cpp
Iosexamp.exe: Iosexamp.cpp

Strfile.exe: ../TestSuite/Test.$(OBJEXT) Strfile.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Strfile.exe Strfile.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Strfile.exe
endif

Strfile.$(OBJEXT): Strfile.cpp
Stype.exe: ../TestSuite/Test.$(OBJEXT) Stype.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Stype.exe Stype.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Stype.exe
endif

Stype.$(OBJEXT): Stype.cpp
Sbufget.exe: ../TestSuite/Test.$(OBJEXT) Sbufget.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Sbufget.exe Sbufget.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Sbufget.exe
endif

Sbufget.$(OBJEXT): Sbufget.cpp
Seeking.exe: ../TestSuite/Test.$(OBJEXT) Seeking.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Seeking.exe Seeking.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Seeking.exe
endif

Seeking.$(OBJEXT): Seeking.cpp
Iofile.exe: ../TestSuite/Test.$(OBJEXT) Iofile.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Iofile.exe Iofile.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Iofile.exe
endif

Iofile.$(OBJEXT): Iofile.cpp
Istring.exe: ../TestSuite/Test.$(OBJEXT) Istring.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Istring.exe Istring.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Istring.exe
endif

Istring.$(OBJEXT): Istring.cpp
Ostring.exe: Ostring.cpp

Walrus.exe: ../TestSuite/Test.$(OBJEXT) Walrus.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Walrus.exe Walrus.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Walrus.exe
endif

Walrus.$(OBJEXT): Walrus.cpp
Strmove.exe: ../TestSuite/Test.$(OBJEXT) Strmove.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Strmove.exe Strmove.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Strmove.exe
endif

Strmove.$(OBJEXT): Strmove.cpp
Format.exe: ../TestSuite/Test.$(OBJEXT) Format.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Format.exe Format.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Format.exe
endif

Format.$(OBJEXT): Format.cpp
Manips.exe: ../TestSuite/Test.$(OBJEXT) Manips.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Manips.exe Manips.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Manips.exe
endif

Manips.$(OBJEXT): Manips.cpp
nl.exe: ../TestSuite/Test.$(OBJEXT) nl.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)nl.exe nl.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	nl.exe
endif

nl.$(OBJEXT): nl.cpp
Effector.exe: ../TestSuite/Test.$(OBJEXT) Effector.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Effector.exe Effector.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Effector.exe
endif

Effector.$(OBJEXT): Effector.cpp
Makemain.exe: ../TestSuite/Test.$(OBJEXT) Makemain.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Makemain.exe Makemain.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Makemain.exe
endif

Makemain.$(OBJEXT): Makemain.cpp
Cppcheck.exe: ../TestSuite/Test.$(OBJEXT) Cppcheck.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Cppcheck.exe Cppcheck.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Cppcheck.exe
endif

Cppcheck.$(OBJEXT): Cppcheck.cpp
Showerr.exe: Showerr.cpp

Datalog.$(OBJEXT): Datalog.cpp

Datagen.exe: Datalog.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) Datagen.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Datagen.exe Datagen.$(OBJEXT) Datalog.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Datagen.exe
endif

Datagen.$(OBJEXT): Datagen.cpp
Datascan.exe: Datalog.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) Datascan.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Datascan.exe Datascan.$(OBJEXT) Datalog.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Datascan.exe
endif

Datascan.$(OBJEXT): Datascan.cpp
NumberPhotos.exe: NumberPhotos.cpp

Breakup.exe: Breakup.cpp

