# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C11
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $(CPPFLAGS) $< $(EXEFLAG)$@


Borland:  \
	SingletonPattern.exe \
	LogFile.$(OBJEXT) \
	UseLog1.$(OBJEXT) \
	UseLog2.exe \
	SingletonPattern2.exe \
	FunctionStaticSingleton.exe \
	Bicycle.$(OBJEXT) \
	BikeTest.exe \
	ShapeFactory1.exe \
	ShapeFactory2.exe \
	AbstractFactory.exe \
	VirtualConstructor.exe \
	InnerClassIdiom.exe \
	ObservedFlower.exe \
	PaperScissorsRock.exe \
	BeeAndFlowers.exe \
	Recycle1.exe \
	Recycle2.exe \
	Trash.$(OBJEXT) \
	TrashStat.$(OBJEXT) \
	TrashProtoInit.$(OBJEXT) \
	fillBin.$(OBJEXT) \
	Recycle3.exe \
	Recycle4.exe \
	DDTrashProtoInit.$(OBJEXT) \
	DoubleDispatch.exe \
	VisitorTrashPInit.$(OBJEXT) \
	TrashVisitor.exe \
	DynaTrash.exe

Microsoft:  \
	SingletonPattern.exe \
	LogFile.$(OBJEXT) \
	UseLog1.$(OBJEXT) \
	UseLog2.exe \
	SingletonPattern2.exe \
	FunctionStaticSingleton.exe \
	Bicycle.$(OBJEXT) \
	BikeTest.exe \
	ShapeFactory1.exe \
	ShapeFactory2.exe \
	AbstractFactory.exe \
	VirtualConstructor.exe \
	InnerClassIdiom.exe \
	ObservedFlower.exe \
	PaperScissorsRock.exe \
	BeeAndFlowers.exe \
	Recycle1.exe \
	Recycle2.exe \
	Trash.$(OBJEXT) \
	TrashStat.$(OBJEXT) \
	TrashProtoInit.$(OBJEXT) \
	fillBin.$(OBJEXT) \
	Recycle3.exe \
	Recycle4.exe \
	DDTrashProtoInit.$(OBJEXT) \
	VisitorTrashPInit.$(OBJEXT) \
	DynaTrash.exe

g++295:  \
	SingletonPattern.exe \
	LogFile.$(OBJEXT) \
	UseLog1.$(OBJEXT) \
	UseLog2.exe \
	SingletonPattern2.exe \
	FunctionStaticSingleton.exe \
	Bicycle.$(OBJEXT) \
	BikeTest.exe \
	ShapeFactory1.exe \
	ShapeFactory2.exe \
	AbstractFactory.exe \
	VirtualConstructor.exe \
	InnerClassIdiom.exe \
	ObservedFlower.exe \
	PaperScissorsRock.exe \
	BeeAndFlowers.exe \
	Recycle1.exe \
	Recycle2.exe \
	Trash.$(OBJEXT) \
	TrashStat.$(OBJEXT) \
	TrashProtoInit.$(OBJEXT) \
	fillBin.$(OBJEXT) \
	Recycle3.exe \
	Recycle4.exe \
	DDTrashProtoInit.$(OBJEXT) \
	DoubleDispatch.exe \
	VisitorTrashPInit.$(OBJEXT) \
	TrashVisitor.exe \
	DynaTrash.exe

g++3:  \
	SingletonPattern.exe \
	LogFile.$(OBJEXT) \
	UseLog1.$(OBJEXT) \
	UseLog2.exe \
	SingletonPattern2.exe \
	FunctionStaticSingleton.exe \
	Bicycle.$(OBJEXT) \
	BikeTest.exe \
	ShapeFactory1.exe \
	ShapeFactory2.exe \
	AbstractFactory.exe \
	VirtualConstructor.exe \
	InnerClassIdiom.exe \
	ObservedFlower.exe \
	PaperScissorsRock.exe \
	BeeAndFlowers.exe \
	Recycle1.exe \
	Recycle2.exe \
	Trash.$(OBJEXT) \
	TrashStat.$(OBJEXT) \
	TrashProtoInit.$(OBJEXT) \
	fillBin.$(OBJEXT) \
	Recycle3.exe \
	Recycle4.exe \
	DDTrashProtoInit.$(OBJEXT) \
	DoubleDispatch.exe \
	VisitorTrashPInit.$(OBJEXT) \
	TrashVisitor.exe \
	DynaTrash.exe

edg:  \
	SingletonPattern.exe \
	LogFile.$(OBJEXT) \
	UseLog1.$(OBJEXT) \
	UseLog2.exe \
	SingletonPattern2.exe \
	FunctionStaticSingleton.exe \
	Bicycle.$(OBJEXT) \
	BikeTest.exe \
	ShapeFactory1.exe \
	ShapeFactory2.exe \
	AbstractFactory.exe \
	VirtualConstructor.exe \
	InnerClassIdiom.exe \
	ObservedFlower.exe \
	PaperScissorsRock.exe \
	BeeAndFlowers.exe \
	Recycle1.exe \
	Recycle2.exe \
	Trash.$(OBJEXT) \
	TrashStat.$(OBJEXT) \
	TrashProtoInit.$(OBJEXT) \
	fillBin.$(OBJEXT) \
	Recycle3.exe \
	Recycle4.exe \
	DDTrashProtoInit.$(OBJEXT) \
	DoubleDispatch.exe \
	VisitorTrashPInit.$(OBJEXT) \
	TrashVisitor.exe \
	DynaTrash.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


SingletonPattern.exe: ../TestSuite/Test.$(OBJEXT) SingletonPattern.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)SingletonPattern.exe SingletonPattern.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	SingletonPattern.exe
endif

SingletonPattern.$(OBJEXT): SingletonPattern.cpp
LogFile.$(OBJEXT): LogFile.cpp

UseLog1.$(OBJEXT): UseLog1.cpp

UseLog2.exe: UseLog1.$(OBJEXT) LogFile.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) UseLog2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)UseLog2.exe UseLog2.$(OBJEXT) UseLog1.$(OBJEXT) LogFile.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	UseLog2.exe
endif

UseLog2.$(OBJEXT): UseLog2.cpp
SingletonPattern2.exe: ../TestSuite/Test.$(OBJEXT) SingletonPattern2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)SingletonPattern2.exe SingletonPattern2.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	SingletonPattern2.exe
endif

SingletonPattern2.$(OBJEXT): SingletonPattern2.cpp
FunctionStaticSingleton.exe: ../TestSuite/Test.$(OBJEXT) FunctionStaticSingleton.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)FunctionStaticSingleton.exe FunctionStaticSingleton.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	FunctionStaticSingleton.exe
endif

FunctionStaticSingleton.$(OBJEXT): FunctionStaticSingleton.cpp
Bicycle.$(OBJEXT): Bicycle.cpp

BikeTest.exe: Bicycle.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) BikeTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)BikeTest.exe BikeTest.$(OBJEXT) Bicycle.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	BikeTest.exe
endif

BikeTest.$(OBJEXT): BikeTest.cpp
ShapeFactory1.exe: ../TestSuite/Test.$(OBJEXT) ShapeFactory1.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)ShapeFactory1.exe ShapeFactory1.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	ShapeFactory1.exe
endif

ShapeFactory1.$(OBJEXT): ShapeFactory1.cpp
ShapeFactory2.exe: ../TestSuite/Test.$(OBJEXT) ShapeFactory2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)ShapeFactory2.exe ShapeFactory2.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	ShapeFactory2.exe
endif

ShapeFactory2.$(OBJEXT): ShapeFactory2.cpp
AbstractFactory.exe: ../TestSuite/Test.$(OBJEXT) AbstractFactory.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)AbstractFactory.exe AbstractFactory.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	AbstractFactory.exe
endif

AbstractFactory.$(OBJEXT): AbstractFactory.cpp
VirtualConstructor.exe: ../TestSuite/Test.$(OBJEXT) VirtualConstructor.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)VirtualConstructor.exe VirtualConstructor.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	VirtualConstructor.exe
endif

VirtualConstructor.$(OBJEXT): VirtualConstructor.cpp
InnerClassIdiom.exe: ../TestSuite/Test.$(OBJEXT) InnerClassIdiom.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)InnerClassIdiom.exe InnerClassIdiom.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	InnerClassIdiom.exe
endif

InnerClassIdiom.$(OBJEXT): InnerClassIdiom.cpp
ObservedFlower.exe: ../TestSuite/Test.$(OBJEXT) ObservedFlower.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)ObservedFlower.exe ObservedFlower.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	ObservedFlower.exe
endif

ObservedFlower.$(OBJEXT): ObservedFlower.cpp
PaperScissorsRock.exe: ../TestSuite/Test.$(OBJEXT) PaperScissorsRock.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)PaperScissorsRock.exe PaperScissorsRock.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	PaperScissorsRock.exe
endif

PaperScissorsRock.$(OBJEXT): PaperScissorsRock.cpp
BeeAndFlowers.exe: ../TestSuite/Test.$(OBJEXT) BeeAndFlowers.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)BeeAndFlowers.exe BeeAndFlowers.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	BeeAndFlowers.exe
endif

BeeAndFlowers.$(OBJEXT): BeeAndFlowers.cpp
Recycle1.exe: ../TestSuite/Test.$(OBJEXT) Recycle1.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Recycle1.exe Recycle1.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Recycle1.exe
endif

Recycle1.$(OBJEXT): Recycle1.cpp
Recycle2.exe: ../TestSuite/Test.$(OBJEXT) Recycle2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Recycle2.exe Recycle2.$(OBJEXT) ../TestSuite/Test.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Recycle2.exe
endif

Recycle2.$(OBJEXT): Recycle2.cpp
Trash.$(OBJEXT): Trash.cpp

TrashStat.$(OBJEXT): TrashStat.cpp

TrashProtoInit.$(OBJEXT): TrashProtoInit.cpp

fillBin.$(OBJEXT): fillBin.cpp

Recycle3.exe: TrashProtoInit.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) fillBin.$(OBJEXT) Trash.$(OBJEXT) TrashStat.$(OBJEXT) Recycle3.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Recycle3.exe Recycle3.$(OBJEXT) TrashProtoInit.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) fillBin.$(OBJEXT) Trash.$(OBJEXT) TrashStat.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Recycle3.exe
endif

Recycle3.$(OBJEXT): Recycle3.cpp
Recycle4.exe: TrashProtoInit.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) fillBin.$(OBJEXT) Trash.$(OBJEXT) TrashStat.$(OBJEXT) Recycle4.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Recycle4.exe Recycle4.$(OBJEXT) TrashProtoInit.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) fillBin.$(OBJEXT) Trash.$(OBJEXT) TrashStat.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	Recycle4.exe
endif

Recycle4.$(OBJEXT): Recycle4.cpp
DDTrashProtoInit.$(OBJEXT): DDTrashProtoInit.cpp

DoubleDispatch.exe: DDTrashProtoInit.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) fillBin.$(OBJEXT) Trash.$(OBJEXT) TrashStat.$(OBJEXT) DoubleDispatch.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)DoubleDispatch.exe DoubleDispatch.$(OBJEXT) DDTrashProtoInit.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) fillBin.$(OBJEXT) Trash.$(OBJEXT) TrashStat.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	DoubleDispatch.exe
endif

DoubleDispatch.$(OBJEXT): DoubleDispatch.cpp
VisitorTrashPInit.$(OBJEXT): VisitorTrashPInit.cpp

TrashVisitor.exe: VisitorTrashPInit.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) fillBin.$(OBJEXT) Trash.$(OBJEXT) TrashStat.$(OBJEXT) TrashVisitor.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)TrashVisitor.exe TrashVisitor.$(OBJEXT) VisitorTrashPInit.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) fillBin.$(OBJEXT) Trash.$(OBJEXT) TrashStat.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	TrashVisitor.exe
endif

TrashVisitor.$(OBJEXT): TrashVisitor.cpp
DynaTrash.exe: TrashProtoInit.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) fillBin.$(OBJEXT) Trash.$(OBJEXT) TrashStat.$(OBJEXT) DynaTrash.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)DynaTrash.exe DynaTrash.$(OBJEXT) TrashProtoInit.$(OBJEXT) ../TestSuite/Test.$(OBJEXT) fillBin.$(OBJEXT) Trash.$(OBJEXT) TrashStat.$(OBJEXT)
ifneq ($(MAKECMDGOALS),Microsoft)
	DynaTrash.exe
endif

DynaTrash.$(OBJEXT): DynaTrash.cpp
